### ISSUE TITLE
Error in Install as a Go Binary

### ISSUE THREAD

**Issue by gnanakeethan** [mabels/s3-streaming-lister#5]
The following command should typically install the library. But it fails. I am unable to run the binary on MacOS without compiling due to security reasons. 

```go install github.com/mabels/eimer-kette/cmd@latest```

The errored output is, 

```
go: github.com/mabels/eimer-kette/cmd@latest: github.com/mabels/eimer-kette@v0.0.7: parsing go.mod:
	module declares its path as: github.com/mabels/s3-streaming-lister
	        but was required as: github.com/mabels/eimer-kette
```

**Comment by gnanakeethan** [comment]
New version needs to be released with 0.0.8

**Comment by gnanakeethan** [comment]
```
go install github.com/mabels/eimer-kette/cmd/eimer-kette@c4d926aa68115319cbec2c76147e9ec5d6eb5df1
```

This command works fine to install.

**Comment by mabels** [comment]
This is not really maintained currently -- sorry for that. If you want to use it i could clean it up.

**Comment by gnanakeethan** [comment]
Is there any way I could help you here? 

Few of my clients want to use the features and I do not want to go back and reinvent the wheel.

**Comment by mabels** [comment]
i will try to make a release today is that ok for you?

**Comment by mabels** [comment]
you know about this --strategy letter --delimiter ""

**Comment by mabels** [comment]
this should work now
go install github.com/mabels/eimer-kette/cmd/eimer-kette@latest
or
go install github.com/mabels/eimer-kette/cmd/eimer-kette@v0.0.8

**Comment by mabels** [comment]
so we have also a v0.0.8 release now

**Comment by gnanakeethan** [comment]
@mabels Yeah. I saw that on the docs. It is working fine. Thanks.  👍🏼
